### ISSUE TITLE
fix upload resume,photo issue

### ISSUE THREAD

**Issue by kundurthivenkatakishore** [b30wulffz/job-portal#6]

**Comment by KarkiKaushal** [comment]
Yeah I m facing the same issue. Whole pipeline method is over my head.

**Comment by KarkiKaushal** [comment]
I have made some changes and now it's working.

**Comment by kundurthivenkatakishore** [comment]
what are the changes?

**Comment by pritam0710** [comment]
> I have made some changes and now it's working.

Can you help me with that, I also got struck that.

**Comment by Kritarth37** [comment]
> 

what changes?

**Comment by YASHMAHAJAN02** [comment]
> I have made some changes and now it's working.
Can you please share the changes?

**Comment by Akulvarshney** [comment]
Can someone help me with the upload resume and profile photo thing?
ASAP! Help will be appreciated.

**Comment by linktoahmad** [comment]
> Can someone help me with the upload resume and profile photo thing? ASAP! Help will be appreciated.
try using the multer version that matches your node version

**Comment by b30wulffz** [comment]
This project is not maintained from last two years, hence updated libraries and depreciated features might cause issues. Feel free to raise a PR.

**Comment by ghost** [comment]
> Can someone help me with the upload resume and profile photo thing? ASAP! Help will be appreciated.

how to solve this . @b30wulffz  can you share this projects design , do you have some rough work or system design how database is handled?

**Comment by ghost** [comment]
can base64 string of a resume stored in database then it should allow us download at recruiters side as well as applicant side.
`<a href="data:application/octet-stream;base64,{{resumeData}}" download="resume.pdf">Download Resume</a>`

**Comment by Akulvarshney** [comment]
> This project is not maintained from last two years, hence updated libraries and depreciated features might cause issues. Feel free to raise a PR.

bro hogya hota toh atte hi nahi yaha par, please look into it and help us solve this issue.

**Comment by Akulvarshney** [comment]
> > Can someone help me with the upload resume and profile photo thing? ASAP! Help will be appreciated.
> > try using the multer version that matches your node version

bro I tried but it started showing new error. Could you please solve the issue and help me giving your repository. so that i can fetch.

**Comment by ghost** [comment]
> > > Can someone help me with the upload resume and profile photo thing? ASAP! Help will be appreciated.
> > > try using the multer version that matches your node version
> 
> bro I tried but it started showing new error. Could you please solve the issue and help me giving your repository. so that i can fetch.

bro progress kha tak hui kha error ara?

**Comment by Akulvarshney** [comment]
> > > > Can someone help me with the upload resume and profile photo thing? ASAP! Help will be appreciated.
> > > > try using the multer version that matches your node version
> > 
> > 
> > bro I tried but it started showing new error. Could you please solve the issue and help me giving your repository. so that i can fetch.
> 
> bro progress kha tak hui kha error ara?

multer ko latest syntax ke saath fix kiya tha.  fir yeh error anne laga "BAD request"

TypeError [ERR_INVALID_ARG_TYPE]: The "body" argument must be of type function or an instance of Blob, ReadableStream, WritableStream, Stream, Iterable, AsyncIterable, or Promise or { readable, writable } pair. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at duplexify (node:internal/streams/duplexify:199:9)
    at Function.Duplex.from (node:internal/streams/duplex:121:10) 
    at pipelineImpl (node:internal/streams/pipeline:260:22)       
    at node:stream/promises:28:5
    at new Promise (<anonymous>)
    at pipeline (node:stream/promises:17:10)
    at D:\CollegePlacementPortal\job-portal\backend\routes\uploadRoutes.js:29:3
    at Layer.handle [as handle_request] (D:\CollegePlacementPortal\job-portal\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CollegePlacementPortal\job-portal\backend\node_modules\express\lib\router\route.js:144:13)
    at done (D:\CollegePlacementPortal\job-portal\backend\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (D:\CollegePlacementPortal\job-portal\backend\node_modules\multer\lib\make-middleware.js:49:68)
    at D:\CollegePlacementPortal\job-portal\backend\node_modules\multer\lib\make-middleware.js:155:11
    at WriteStream.<anonymous> (D:\CollegePlacementPortal\job-portal\backend\node_modules\multer\storage\disk.js:43:9)
    at WriteStream.emit (node:events:525:35)
    at finish (node:internal/streams/writable:756:10) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by ghost** [comment]
i think bina multer ka solve kr sakta ha frontend ma base64 string resume ka nikal lete ha..then usa hi store krwa denga database ma 

> can base64 string of a resume stored in database then it should allow us download at recruiters side as well as applicant side. `<a href="data:application/octet-stream;base64,{{resumeData}}" download="resume.pdf">Download Resume</a>`

then isa use kr lenga frontend or backend ma .
pr image ka issue ha

**Comment by Akulvarshney** [comment]
> 

bro

> i think bina multer ka solve kr sakta ha frontend ma base64 string resume ka nikal lete ha..then usa hi store krwa denga database ma
> 
> > can base64 string of a resume stored in database then it should allow us download at recruiters side as well as applicant side. `<a href="data:application/octet-stream;base64,{{resumeData}}" download="resume.pdf">Download Resume</a>`
> 
> then isa use kr lenga frontend or backend ma . pr image ka issue ha

bro download toh baadme krenge yaha toh upload hi nhi ho rha. help me with uploading the resume first.

**Comment by ghost** [comment]
frontend sa backned ma resume jara kya? print krka check kia?

**Comment by Akulvarshney** [comment]
> frontend sa backned ma resume jara kya? print krka check kia?
voh public folder mein new file name ke saath store toh ho rha hai. How will i check ki backend mein jaa rha hai?

**Comment by ghost** [comment]
```
router.post("/resume", upload.single("file"), (req, res) => {
  const { file } = req;
  if (file.detectedFileExtension != ".pdf") {
    res.status(400).json({
      message: "Invalid format",
    });
  } else {
    const filename = `${uuidv4()}${file.detectedFileExtension}`;

    pipeline(
      file.stream,
      fs.createWriteStream(`${__dirname}/../public/resume/${filename}`)
    )
      .then(() => {
        res.send({
          message: "File uploaded successfully",
          url: `/host/resume/${filename}`,
        });
      })
      .catch((err) => {
        res.status(400).json({
          message: "Error while uploading",
        });
      });
  }
});
```
upload routes .js ma changes krna pdenga ya folder ma save krna ka code likh rkha @b30wulffz  na or mongodb ma store krna ka code likhna ha yaha pr

**Comment by Akulvarshney** [comment]
> ```
> router.post("/resume", upload.single("file"), (req, res) => {
>   const { file } = req;
>   if (file.detectedFileExtension != ".pdf") {
>     res.status(400).json({
>       message: "Invalid format",
>     });
>   } else {
>     const filename = `${uuidv4()}${file.detectedFileExtension}`;
> 
>     pipeline(
>       file.stream,
>       fs.createWriteStream(`${__dirname}/../public/resume/${filename}`)
>     )
>       .then(() => {
>         res.send({
>           message: "File uploaded successfully",
>           url: `/host/resume/${filename}`,
>         });
>       })
>       .catch((err) => {
>         res.status(400).json({
>           message: "Error while uploading",
>         });
>       });
>   }
> });
> ```
> 
> upload routes .js ma changes krna pdenga ya folder ma save krna ka code likh rkha @b30wulffz na or mongodb ma store krna ka code likhna ha yaha pr

still it says bad request. 😫😫😫

**Comment by Akulvarshney** [comment]
Any more suggestions anyone?

**Comment by Akulvarshney** [comment]
> frontend sa backned ma resume jara kya? print krka check kia?

bro backend mein toh jaa rha hai 
<img width="306" alt="image" src="https://user-images.githubusercontent.com/50898260/227730399-0082dbcb-fe80-443b-8a2f-6961a692a260.png">

but bad request kyo dikha rha hai.

**Comment by ghost** [comment]
code ka screenshot bhejo jha  pr changes kia

**Comment by Akulvarshney** [comment]
> code ka screenshot bhejo jha pr changes kia

const express = require("express");
const multer = require("multer");
const fs = require("fs");
const { v4: uuidv4 } = require("uuid");
const { promisify } = require("util");
const path = require("path");

const pipeline = promisify(require("stream").pipeline);

const router = express.Router();

const upload = multer({
  dest: "../public/resume",
});

router.post("/resume", upload.single("file"), (req, res) => {
  const { file } = req;
  console.log(file);
  if (file.originalname != ".pdf") {
    res.status(400).json({
      message: "Invalid format",
    });
  } else {
    const filename = `${uuidv4()}${file.originalname}`;

    pipeline(
      file.stream,
      fs.createWriteStream(`${__dirname}/../public/resume/${filename}`)
    )
      .then(() => {
        res.send({
          message: "File uploaded successfully",
          url: `/host/resume/${filename}`,
        });
      })
      .catch((err) => {
        console.log(err);
        res.status(400).json({
          message: "Error while uploading",
        });
      });
  }
});
router.post("/profile", upload.single("file"), (req, res) => {
  const { file } = req;
  const fileExtension = path.extname(file.originalname);
  if (fileExtension != ".jpg" && fileExtension != ".png") {
    res.status(400).json({
      message: "Invalid format",
    });
  } else {
    const filename = `${uuidv4()}${fileExtension}`;

    pipeline(
      file.stream,
      fs.createWriteStream(`${__dirname}/../public/profile/${filename}`)
    )
      .then(() => {
        res.send({
          message: "Profile image uploaded successfully",
          url: `/host/profile/${filename}`,
        });
      })
      .catch((err) => {
        res.status(400).json({
          message: "Error while uploading",
        });
      });
  }
});

module.exports = router;

**Comment by ghost** [comment]
The source code tries to send resume to server then server will send resume to database. The database will create a link of the resume. Then resume's link of the applicant will be stored along with his details. I dont know why did he complicated it too much instead he could store directly to applicant's collection.

**Comment by ghost** [comment]
@Akulvarshney 
 changed the fileUploadInput.js
```
import { useState } from "react";
import { Grid, Button, TextField, LinearProgress } from "@material-ui/core";
import { CloudUpload } from "@material-ui/icons";
const FileUploadInput = (props) => {
  const [file,setFile]=useState()
  const { identifier, handleInput } = props;
  const [uploadPercentage, setUploadPercentage] = useState(0);

  const handleUpload = (e) => {
    const reader = new FileReader();
    reader.readAsBinaryString(e.target.files[0]);
    reader.onload = () => {
      handleInput(identifier,window.btoa(reader.result));
    };      
  };

  return (
    <Grid container item xs={12} direction="column" className={props.className}>
      <Grid container item xs={12} spacing={0}>
        <Grid item xs={3}>
          <Button
            variant="contained"
            color="primary"
            component="label"
            style={{ width: "100%", height: "100%" }}
          >
            {props.icon}
            <input
              type="file"
              style={{ display: "none" }}
              onChange={(event) => {
                setUploadPercentage(0);
                setFile(event.target.files[0]);
                handleUpload(event);
              }}
            />
          </Button>
        </Grid>
        <Grid item xs={6}>
          <TextField
            label={props.label}
            value={file ? file.name || "" : ""}
            InputProps={{
              readOnly: true,
            }}
            variant="outlined"
            style={{ width: "100%" }}
          />
        </Grid>
        <Grid item xs={3}>
          <Button
            variant="contained"
            color="secondary"
            style={{ width: "100%", height: "100%" }}
            onClick={() => handleUpload()}
            disabled={file ? false : true}
          >
            <CloudUpload />
          </Button>
        </Grid>
      </Grid>
      {uploadPercentage !== 0 ? (
        <Grid item xs={12} style={{ marginTop: "10px" }}>
          <LinearProgress variant="determinate" value={uploadPercentage} />
        </Grid>
      ) : null}
    </Grid>
  );
};

export default FileUploadInput;
```
then in Job applications file  downloading resume using this code
```
 <a href={`data:application/octet-stream;base64,${application.jobApplicant.resume}`} download="resume.pdf">
            <Button
              variant="contained"
              className={classes.statusBlock}
              color="primary"
            >
              Download Resume
            </Button>
            </a>
```
This worked

**Comment by Akulvarshney** [comment]
@PanwarAyush 

Bro! 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/50898260/227830665-5c1aa0b6-be6e-43fa-ab8d-3028e29fe80c.png">

**Comment by Akulvarshney** [comment]
@PanwarAyush you can do it bro, com'on.

**Comment by Akulvarshney** [comment]
chal gya bro, chal gya

**Comment by ghost** [comment]
@Akulvarshney  ok by the way you can reference this https://github.com/PanwarAyush/Job-Portal
i have made changes to it but you have to insert your MONGO db uri in server.js my uri won't work now.
I have also removed profile image upload part for now.

**Comment by ghost** [comment]
I am trying to add score resume feature on recruiter side but how to manipulate database , it is complicated for me.

**Comment by muskank101** [comment]
Hey, anyone has completed it?

**Comment by VISHNU-2003** [comment]
Hello everyone the issue has been resolved the code has some changes in the backend part
path:  job-portal-main>>backend>>routes>>uploadRoutes.js

here is the corrected code of it:

const express = require("express");
const multer = require("multer");
const fs = require("fs");
const { v4: uuidv4 } = require("uuid");
const { promisify } = require("util");

const pipeline = promisify(require("stream").pipeline);

const router = express.Router();

const upload = multer();

router.post("/resume", upload.single("file"), (req, res) => {
  const { file } = req;
  if (file.detectedFileExtension != ".pdf") {
    res.status(400).json({
      message: "Invalid format",
    });
  } else {
    const filename = `${uuidv4()}${file.detectedFileExtension}`;

    pipeline(
      file.stream,
      fs.createWriteStream(`${__dirname}/../public/resume/${filename}`)
    )
      .then(() => {
        res.send({
          message: "File uploaded successfully",
          url: `/host/resume/${filename}`,
        });
      })
      .catch((err) => {
        res.status(400).json({
          message: "Error while uploading",
        });
      });
  }
});

router.post("/profile", upload.single("file"), (req, res) => {
  const { file } = req;
  if (
    file.detectedFileExtension != ".jpg" &&
    file.detectedFileExtension != ".png"
  ) {
    res.status(400).json({
      message: "Invalid format",
    });
  } else {
    const filename = `${uuidv4()}${file.detectedFileExtension}`;

    pipeline(
      file.stream,
      fs.createWriteStream(`${__dirname}/../public/profile/${filename}`)
    )
      .then(() => {
        res.send({
          message: "Profile image uploaded successfully",
          url: `/host/profile/${filename}`,
        });
      })
      .catch((err) => {
        res.status(400).json({
          message: "Error while uploading",
        });
      });
  }
});

module.exports = router;

const express = require("express");
const multer = require("multer");
const fs = require("fs");
const { v4: uuidv4 } = require("uuid");
const { promisify } = require("util");

const pipeline = promisify(require("stream").pipeline);

const router = express.Router();

const upload = multer();

router.post("/resume", upload.single("file"), (req, res) => {
  const { file } = req;
  if (file.detectedFileExtension != ".pdf") {
    res.status(400).json({
      message: "Invalid format",
    });
  } else {
    const filename = `${uuidv4()}${file.detectedFileExtension}`;

    pipeline(
      file.stream,
      fs.createWriteStream(`${__dirname}/../public/resume/${filename}`)
    )
      .then(() => {
        res.send({
          message: "File uploaded successfully",
          url: `/host/resume/${filename}`,
        });
      })
      .catch((err) => {
        res.status(400).json({
          message: "Error while uploading",
        });
      });
  }
});

router.post("/profile", upload.single("file"), (req, res) => {
  const { file } = req;
  if (
    file.detectedFileExtension != ".jpg" &&
    file.detectedFileExtension != ".png"
  ) {
    res.status(400).json({
      message: "Invalid format",
    });
  } else {
    const filename = `${uuidv4()}${file.detectedFileExtension}`;

    pipeline(
      file.stream,
      fs.createWriteStream(`${__dirname}/../public/profile/${filename}`)
    )
      .then(() => {
        res.send({
          message: "Profile image uploaded successfully",
          url: `/host/profile/${filename}`,
        });
      })
      .catch((err) => {
        res.status(400).json({
          message: "Error while uploading",
        });
      });
  }
});

module.exports = router;

![Screenshot (2804)](https://github.com/b30wulffz/job-portal/assets/87386224/724623be-be7f-48ba-92d6-f75aee1434d4)

**Comment by muskank101** [comment]
Hey, can you specifically mention the points where you've made changes

**Comment by muskank101** [comment]
I need urgent assistance! plz help

**Comment by linktoahmad** [comment]
Anyone having file upload issue please use the multer version comparable woth node version.. 
Use the versions specified in package.json in the project

**Comment by muskank101** [comment]
What does it mean to have comparable version?

**Comment by VISHNU-2003** [comment]
> Hey, can you specifically mention the points where you've made changes

I've completely replaced the content of the file in the backend:

Path: job-portal-main >> backend >> routes >> uploadRoutes.js

You can find the updated code in 
[uploadRoutes.js.txt](https://github.com/b30wulffz/job-portal/files/15222090/uploadRoutes.js.txt).

Please paste this entire code into the specified file and run the server. If you encounter any issues or need further assistance, feel free to reach out to me via LinkedIn: 
[Alapati Vishnu Vardhan](https://www.linkedin.com/in/alapati-vishnu-vardhan-0523501b7/).
